-- Private intake queue for restaurants that are not yet in ChowdaQuest.
-- Public visitors may submit suggestions but cannot read or approve them.

create table if not exists public.restaurant_suggestions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 120),
  town text not null check (char_length(trim(town)) between 1 and 80),
  website_url text check (website_url is null or char_length(website_url) <= 500),
  suggested_category text not null check (suggested_category in ('ri', 'ne', 'manhattan', 'cakes', 'lobster', 'stuffies')),
  suggested_by text not null check (char_length(trim(suggested_by)) between 1 and 120),
  notes text check (notes is null or char_length(notes) <= 2000),
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  created_at timestamptz not null default now()
);

alter table public.restaurant_suggestions enable row level security;

drop policy if exists "Anyone can suggest a restaurant" on public.restaurant_suggestions;
create policy "Anyone can suggest a restaurant"
on public.restaurant_suggestions
for insert
to anon, authenticated
with check (status = 'pending');

grant insert on public.restaurant_suggestions to anon, authenticated;
grant usage, select on sequence public.restaurant_suggestions_id_seq to anon, authenticated;
